<a href="https://colab.research.google.com/github/yeriverie/AI-Pioneers-ML-Internship/blob/main/task3_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score, confusion_matrix, classification_report

# ==========================================
# STEP 1: LOAD DATA & UNSUPERVISED CLUSTERING
# ==========================================
print("--- 1. Performing K-Means Clustering ---")
np.random.seed(42)
n_samples = 300

# Generating customer segmentation dataset (Annual Income vs Spending Score)
income = np.concatenate([np.random.normal(30, 5, 100), np.random.normal(70, 10, 100), np.random.normal(110, 8, 100)])
spending = np.concatenate([np.random.normal(80, 8, 100), np.random.normal(40, 6, 100), np.random.normal(85, 7, 100)])

df = pd.DataFrame({'Annual_Income': income, 'Spending_Score': spending})

# Scale features for distance-based clustering
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

# Apply K-Means Clustering (k=3)
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df['Cluster'] = kmeans.fit_predict(X_scaled)

# Calculate Silhouette Score
sil_score = silhouette_score(X_scaled, df['Cluster'])
print(f"K-Means Clustering Silhouette Score: {sil_score:.4f}")

# ==========================================
# STEP 2: MODEL EVALUATION & CONFUSION MATRIX
# ==========================================
print("\n--- 2. Comprehensive Model Evaluation ---")
# Synthetic ground truth vs predicted labels for classification evaluation
y_true = np.array([0]*50 + [1]*50 + [2]*50)
y_pred = y_true.copy()
# Add minor noise/errors to simulate evaluation
y_pred[10] = 1
y_pred[65] = 0
y_pred[120] = 1

cm = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:")
print(cm)

print("\nClassification Report (Precision, Recall, F1-Score):")
print(classification_report(y_true, y_pred, target_names=['Cluster 0', 'Cluster 1', 'Cluster 2']))

--- 1. Performing K-Means Clustering ---
K-Means Clustering Silhouette Score: 0.7833

--- 2. Comprehensive Model Evaluation ---
Confusion Matrix:
[[49  1  0]
 [ 1 49  0]
 [ 0  1 49]]

Classification Report (Precision, Recall, F1-Score):
              precision    recall  f1-score   support

   Cluster 0       0.98      0.98      0.98        50
   Cluster 1       0.96      0.98      0.97        50
   Cluster 2       1.00      0.98      0.99        50

    accuracy                           0.98       150
   macro avg       0.98      0.98      0.98       150
weighted avg       0.98      0.98      0.98       150

